openapi: 3.0.0
info:
    title: API
    version: 0.0.0
    description: REST API
    license:
        name: MIT License
        url: "https://opensource.org/licenses/MIT"
paths:
    /sync:
        summary: Sync devices
        get:
            responses:
                "202":
                    description: success
                "500":
                    $ref: "#/components/responses/Error"
            summary: Sync devices
components:
    schemas:
        ErrResponse:
            description: Error response
            required:
                - msg
                - requestID
                - HTTPStatusCode
            type: object
            properties:
                msg:
                    description: The message explaining the error
                    type: string
                requestID:
                    description: The request id to track errors
                    type: string
                HTTPStatusCode:
                    description: The HTTP response code
                    type: integer
    responses:
        Error:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/ErrResponse"
            description: "An unknown error has occurred on the server.  Please see the
                message in the response."
    
