name: Deploy

on:
  push
  # release:
  #   types: [released]
env:
  IMAGE_NAME: magna5/lm2cw

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_APPID }}","clientSecret":"${{ secrets.AZURE_PASSWORD }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT }}", "resourceManagerEndpointUrl": "https://management.azure.com/"}'
      
      - uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          docker build . -t ghcr.io/$IMAGE_NAME:$VERSION
          docker push ghcr.io/$IMAGE_NAME:$VERSION

      # - name: 'Deploy to Azure Container Instances'
      #   uses: 'azure/aci-deploy@v1'
      #   with:
      #     resource-group: contoso
      #     dns-name-label: url-for-container
      #     image: contoso.azurecr.io/nodejssampleapp:${{ github.sha }}
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     name: contoso-container
      #     location: 'west us'
